### ISSUE TITLE
Create design

### ISSUE THREAD

**Issue by evgenyshiryaev** [tigerdevpool/browser-wallet#6]
Prepare design for wallet

**Comment by evgenyshiryaev** [comment]
https://overflow.io/s/2FD75S/

**Comment by maximov-ru** [comment]
archived extension: 
[dist.zip](https://github.com/tigerdevpool/browser-wallet/files/2538105/dist.zip)

**Comment by maximov-ru** [comment]
[dist.zip](https://github.com/tigerdevpool/browser-wallet/files/2557290/dist.zip)
version from 07.11.2018
